#!/usr/bin/python

from socket import *
from time import sleep

#import pdb

myHost=gethostname()
#myHost='ha32163'

s=socket(AF_INET, SOCK_DGRAM)
s.bind(('',12345))
while(1):
#    pdb.set_trace()
    m=s.recvfrom(4096)
    print('len(m)='+str(len(m)))

    print('len(m[0])='+str(len(m[0])))    
    print(m[0])
    print('len(m[1])='+str(len(m[1])))    
    print(m[1])  

    print('Responding with ' + myHost)
    sleep(1)
    s.sendto(myHost.encode('ascii'),(m[1][0],12345))

    print("\n")
